apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  N8N_BASIC_AUTH_USER: YWRtaW4= # base64 encoded value of 'admin'
  N8N_BASIC_AUTH_PASSWORD: YWxwLTMzNDIyMDI1 # base64 encoded value of 'alp-***'