apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  N8N_BASIC_AUTH_USER: YWRtaW4= # base64 para 'admin'
  N8N_BASIC_AUTH_PASSWORD: xxx # senha base64
  N8N_RUNNERS_AUTH_TOKEN: rhXErCf4bQ+iQsTZPNNeGm1T4A9QO0UKhcJtXT6XIYU= #token gerado aleatoriamente para autenticação dos runners